version: '2'

services:
    tomcat: 
      build: 
        context: ./java
        dockerfile: 'Dockerfile'
      volumes:
        - ./tomcat/webapps:/usr/local/tomcat/webapps
        - ./tomcat/logs:/usr/local/tomcat/logs
      ports:
          - "8081:8080"
      networks:
          - "netName1"

networks:
    netName1:
      driver: bridge
