version: '2'

services:
    applications:
      image: tianon/true
      volumes:
        - ./code:/var/www
        - ./code/tomcat/webapps:/usr/local/tomcat/webapps


    tomcat: 
      image: tomcatdocker_tomcat:latest
      volumes_from:
        - applications
      volumes:
        - ./tomcat/logs:/usr/local/tomcat/logs
      ports:
        - "8081:8080"
      links:
        - mysql:mysql  
      networks:
        - "netName1"

    php-fpm:  
      image: tomcatdocker_php-fpm:latest
      volumes_from:
        - applications
      volumes:
        - ./php/php.ini:/usr/local/etc/php/php.ini
      expose:
        - "9000"
      links:
        - mysql:mysql    
      networks:
        - "netName1"
    
    nginx:
      image: tomcatdocker_nginx:latest
      volumes_from:
        - applications
      volumes:
        - ./nginx/logs/nginx/:/var/log/nginx
        - ./nginx/sites/:/etc/nginx/sites-available
      ports:
        - "82:80"
        - "444:443"
      links:
        - mysql:mysql
      networks:
        - "netName1"

    
    mysql: 
      image: mysql:5.7
      restart: always
      environment:
        - MYSQL_DATABASE=service_platform
        - MYSQL_USER=mysql
        - MYSQL_PASSWORD=123456
        - MYSQL_ROOT_PASSWORD=123456
      volumes:
        - ./mysql/data/mysql:/var/lib/mysql
        - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
        - "8090:3306"
      networks:
          - "netName1"

networks:
    netName1:
      driver: bridge
